### ISSUE TITLE
Look at Emma Salesforce Integration

### ISSUE THREAD

**Issue by brettevans** [codefordenver/rmmfi#15]

**Comment by dkoloditch** [comment]
Notes:
- around since 2011 and one of the first things used for emma's api
- uses webhooks
- changes on either system are mirrored on the other system
- install via SF AppExchange
- email data (opens, clicks, shares, opt-outs) is tracked and updated in SF (visible in history) for every synced member
- email data usable in dashboards and reports

Links:
- http://tech.myemma.com/salesforce-and-emma/
- http://myemma.com/email-marketing-integrations/crm-email-integration/salesforce
- https://www.youtube.com/watch?v=N6XfVOgMX1s (good demo)

Upshot: integration seems pretty easy and straightforward.
