### ISSUE TITLE
Create First Email Sent to Volunteer

### ISSUE THREAD

**Issue by brettevans** [codefordenver/rmmfi#19]
Set up basic template

**Comment by wdoug** [comment]
Add link to survey form

**Comment by hendrang** [comment]
1. Created email template named "Potential Volunteer Survey". Content needs to be updated with the Survey link. In addition, we need to consult with Brendan about the content wording.
2. Added RMMFI logo into shared document so we have email letterhead
3. Added a new workflow for contact since the data team decided to use contact instead of lead.
4. Tested by adding "Hendra Ng" into the contact. I verified that email is received.
